version: "3"

services:
  app:
    build:
      context: ./loa-cms
    container_name: loa-cms
    restart: unless-stopped
    environment:
      NODE_ENV: production
      INSTANCE_UNIX_SOCKET: ${INSTANCE_UNIX_SOCKET}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DB_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./app:/srv/app
    ports:
      - 127.0.0.1:1337:8080
    depends_on:
      - cloudsql-proxy

  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: /cloud_sql_proxy --dir=/cloudsql -instances=loa-cms-371211:europe-west8:strapi-docked-db=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json
    ports:
      - 5432:5432
    volumes:
      - ./credentials.json:/secrets/cloudsql/credentials.json
    restart: always

  # db:
  #   image: postgres:14
  #   container_name: loacms_db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: app
  #     POSTGRES_USER: db_username
  #     POSTGRES_PASSWORD: db_password
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
